/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4;

import javax.swing.JOptionPane;

/**
 *
 * @author pared
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmetros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioTerreno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCuoInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCuotasRestantes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Inmobilaria DuFactors");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("*Metros Cuadrados (m^2):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 190, 33));

        txtmetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmetrosActionPerformed(evt);
            }
        });
        txtmetros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmetrosKeyTyped(evt);
            }
        });
        jPanel1.add(txtmetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio del Terrero:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtPrecioTerreno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioTerrenoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecioTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("*Valor m^2: $80000");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Valor Cuota Inicial (35%): ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtCuoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuoInicialKeyTyped(evt);
            }
        });
        jPanel1.add(txtCuoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Monto a Pagar Restante (12 Cuotas):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtCuotasRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuotasRestantesActionPerformed(evt);
            }
        });
        txtCuotasRestantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotasRestantesKeyTyped(evt);
            }
        });
        jPanel1.add(txtCuotasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, -1));

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        long op,op2,op3, metros, precmetros= 80000,cuotini=35, valormet,cuotas= 12, conversion;
        String ValorTerreno, CuotaInicial, CuotasRestantes;
       
        if (txtmetros.getText().trim().isEmpty())
        {
          JOptionPane.showMessageDialog(this, "Ingrese los Metros", "Error", JOptionPane.ERROR_MESSAGE);
          txtmetros.requestFocusInWindow();
        
        }
        else {
        metros= Long.parseLong(txtmetros.getText());
        op= precmetros*metros;
        op2= (op*cuotini)/100;
        op3= (op-op2)/cuotas;
        
        ValorTerreno= String.valueOf(op);
        CuotaInicial= String.valueOf(op2);
        CuotasRestantes= String.valueOf(op3);
        
        txtPrecioTerreno.setText(ValorTerreno);
        txtCuoInicial.setText(CuotaInicial);
        txtCuotasRestantes.setText(CuotasRestantes);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCuotasRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotasRestantesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCuotasRestantesActionPerformed

    private void txtPrecioTerrenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioTerrenoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) 
          { 
              getToolkit().beep(); 
              evt.consume();      
          }
         
          if(!Character.isLetter(c)) 
          { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtPrecioTerrenoKeyTyped

    private void txtCuoInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuoInicialKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) 
          { 
              getToolkit().beep(); 
              evt.consume();      
          }
         
          if(!Character.isLetter(c)) 
          { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtCuoInicialKeyTyped

    private void txtCuotasRestantesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotasRestantesKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) 
          { 
              getToolkit().beep(); 
              evt.consume();      
          }
         
          if(!Character.isLetter(c)) 
          { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtCuotasRestantesKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtCuoInicial.setText("");
        txtCuotasRestantes.setText("");
        txtPrecioTerreno.setText("");
        txtmetros.setText("");
        
        txtmetros.requestFocusInWindow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmetrosActionPerformed

    private void txtmetrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmetrosKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) 
          { 
              getToolkit().beep(); 
              evt.consume();      
          }
    }//GEN-LAST:event_txtmetrosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCuoInicial;
    private javax.swing.JTextField txtCuotasRestantes;
    private javax.swing.JTextField txtPrecioTerreno;
    private javax.swing.JTextField txtmetros;
    // End of variables declaration//GEN-END:variables
}
